### ISSUE TITLE
Tech spec for API

### ISSUE THREAD

**Issue by tinaking28** [JumboCode/OCCUR#6]
Tech spec for API should include: 

- What methods (get, delete, put, etc) we need in our endpoint

- What data will be in the requests and responses, what form they will be in, etc

- explore schemas and whether they are necessary in this context

This will **require** collaboration with the frontend team as they will be sending requests to the API.
Also, this must be completed before starting work on the API Endpoint.

**Comment by Kmukasa** [comment]
Completed
